version: "2.1"
services:
  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - AUTO_UPDATE=true #optional
#      - HTTP_PROXY="http://10.10.102.105:20007"
    volumes:
      - ./data:/config
      - ./downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped